---
- hosts: bingo,postgresql
  tasks:
    - name: Create bingo config dir
      become: true
      file: 
        path: /opt/bingo
        state: directory
    - name: Copy bingo config
      become: true
      ansible.builtin.copy:
        dest: /opt/bingo/config.yaml
        content: |
          student_email: qamo@yandex.ru
          postgres_cluster:
            hosts:
            - address: {{ hostvars[groups['postgresql'][0]]['ansible_host'] }}
              port: 5432
            user: {{ pg_username }}
            password: {{ pg_password }}
            db_name: {{ pg_dbname }}
            ssl_mode: disable
            use_closest_node: false  
- hosts: bingo
  tasks:
    - name: apt-get update
      become: true
      ansible.builtin.apt:
        update_cache: yes
    - name: Install python3-pip
      become: true
      ansible.builtin.package:
        name: python3-pip
        state: present
    - name: Install python package docker
      ansible.builtin.pip:
        name: docker
    - name: Restart bingo containers
      ansible.builtin.command:
        argv:
          - docker
          - restart
          - coi-bingo-1 #TODO fix hardcoded value