#cloud-config
runcmd:
  - |
    #curl -H Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/attributes/lb
    # proxy cache folder creation
    mkdir /opt/nginx_cache && chown nginx:nginx /opt/nginx_cache && chmod 770 /opt/nginx_cache
    apt-get update
    apt install -y nginx
    rm -rf /etc/nginx/sites-enabled/* && rm -rf /etc/nginx/conf.d/*
    cat <<EOF >/etc/nginx/conf.d/bingo.conf
      upstream bingo {
          server 158.160.134.71:8080;
      }
      proxy_cache_path /opt/nginx_cache levels=1:2 keys_zone=bingo:15m max_size=1G;
      server {
          listen 80;
          # listen 443 ssl;
          # listen 443 quic reuseport;
          # ssl_certificate     certs/bingo.crt;
          # ssl_certificate_key certs/bingo.key;
          location /long_dummy {
              add_header Alt-Svc 'h3=":443"; ma=86400';
              proxy_pass http://bingo;
              proxy_cache bingo;
              proxy_cache_valid 1m;
              add_header X-Proxy-Cache \$upstream_cache_status;
              proxy_set_header Host \$http_host;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$scheme;
          }
          location / {
              add_header Alt-Svc 'h3=":443"; ma=86400';
              proxy_pass http://bingo;
              proxy_set_header Host \$http_host;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$scheme;
          }
      }
    EOF

    systemctl reload nginx