---
- hosts: postgresql
  pre_tasks:
    - name: Install acl
      become: true
      ansible.builtin.package:
        name: acl
        state: present
    - name: Install bingo
      become: true
      ansible.builtin.get_url:
        url: "{{ bingo_source }}"
        dest: /usr/bin/bingo
        mode: '755'
    - name: Create an xfs filesystem on SSD
      become: true
      community.general.filesystem:
        fstype: xfs
        dev: /dev/vdb
    - name: Mount SSD
      become: true
      ansible.posix.mount:
        path: /var/lib/postgresql
        src: /dev/vdb
        fstype: xfs
        opts: defaults
        state: mounted

  roles:
    - role: anxs.postgresql
      become: yes
      vars:
        # see https://github.com/ANXS/postgresql/issues/523
        ansible_python_interpreter: "/usr/bin/python3"
        postgresql_shared_buffers: 4096MB
        postgresql_work_mem: 128MB
        postgresql_listen_addresses: "*"
        postgresql_pg_hba_default:
          - { type: local, database: all, user: all, address: "",             method: "{{ postgresql_default_auth_method }}", comment: '"local" is for Unix domain socket connections only' }
          - { type: host,  database: all, user: all, address: "127.0.0.1/32", method: "{{ postgresql_default_auth_method_hosts }}", comment: "IPv4 local connections:" }
          - { type: host,  database: all, user: all, address: "0.0.0.0/0", method: "{{ postgresql_default_auth_method_hosts }}", comment: "IPv4 local connections:" }
          - { type: local, database: all, user: "{{ postgresql_admin_user }}", address: "", method: "peer map=root_as_{{ postgresql_admin_user }}", comment: "Local root Unix user, passwordless access" }
        postgresql_databases:
          - name: "{{ pg_dbname }}"
            owner: "{{ pg_username }}"
        postgresql_users:
          - name: "{{ pg_username }}"
            # TODO secure the passwords
            pass: pass
            encrypted: yes  # if password should be encrypted, postgresql >= 10 does only accepts encrypted passwords
            state: "present"    # optional; one of 'present', 'absent'

  post_tasks:
    - name: Import bingo data
      ansible.builtin.command: bingo prepare_db