---
- hosts: balancer
  roles:
    - role: nginxinc.nginx
      become: true
  post_tasks:
    - name: Create nginx cache folder
      become: true
      file: 
        path: /opt/nginx_cache
        state: directory
        owner: nginx
        group: nginx
    - name: Create nginx certs folder
      become: true
      file: 
        path: /etc/nginx/certs
        state: directory
    - name: Copy nginx TLS key
      become: true
      ansible.builtin.copy:
        dest: /etc/nginx/certs/bingo.key
        content: "{{ bingo_key }}"
    - name: Copy nginx TLS certificate
      become: true
      ansible.builtin.copy:
        dest: /etc/nginx/certs/bingo.crt
        content: "{{ bingo_cert }}"

    - name: Copy nginx bingo.conf
      become: true
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/bingo.conf
        #TODO Let's think about prettifying later
        content: |
          upstream bingo {
              server {{ hostvars[groups['bingo'][0]]['ansible_host'] }}:13526;
              server {{ hostvars[groups['bingo'][1]]['ansible_host'] }}:13526;
          }
          proxy_cache_path /opt/nginx_cache levels=1:2 keys_zone=bingo:15m max_size=1G;
          server {
              listen 80;
              listen 443 ssl;
              listen 443 quic reuseport;

              ssl_certificate     certs/bingo.crt;
              ssl_certificate_key certs/bingo.key;

              location /long_dummy {
                  add_header Alt-Svc 'h3=":443"; ma=86400';
                  proxy_pass http://bingo;
                  proxy_cache bingo;
                  proxy_cache_valid 1m;
                  add_header X-Proxy-Cache $upstream_cache_status;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
              location / {
                  add_header Alt-Svc 'h3=":443"; ma=86400';
                  proxy_pass http://bingo;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
          
    - name: Reload service nginx
      become: true
      ansible.builtin.systemd:
        name: nginx.service
        state: reloaded