---
- hosts: balancer
  roles:
    - role: nginxinc.nginx
      become: yes
  post_tasks:
    - name: Create nginx bingo.conf
      become: true
      file: 
        path: /opt/bingo
        state: directory
    - name: Copy nginx bingo.conf
      become: true
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/bingo.conf
        #TODO Let's think about prettifying later
        content: |
          upstream bingo {
              server {{ hostvars[groups['bingo'][0]]['ansible_host'] }}:13526;
              server {{ hostvars[groups['bingo'][1]]['ansible_host'] }}:13526;
          }

          server {
              listen 80;
                  
              location / {
                  proxy_pass http://bingo;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }