folder_id: b1gla0rq0g8628fo9b0o
inventory_file: inventory.yaml
network:
  name: prod-bingo-network
  subnets: 
    prod-bingo-subnet:
      v4_cidr_blocks: ["10.6.0.0/24"]
      zone: ru-central1-b

# registries:
#   default:
#     labels:
#       env: prod

service_accounts:
  bingo-ig-sa-prod:
    roles: 
      - editor # https://cloud.yandex.com/en/docs/compute/quickstart/ig
      #  To be able to create, update, and delete group instances, assign the editor role to the service account. 

instance_groups:
  prod-bingo:
    ansible_groups:
      - bingo
    service_account: bingo-ig-sa-prod
    resources:
      cores: 2
      memory: 1 #Gb
      disk_size: 30 #Gb
    network:
      subnet: prod-bingo-subnet
      nat: false
    lb:
      port: 8080
      target_port: 13526
      healthcheck: 
        interval: 2
        unhealthy_threshold: 2
        port: 13526
        path: /ping
    metadata: 
      # treated as a file path
      docker-compose: 
        file: ../build/prod-docker-compose.yml
      ssh-keys: 
        username: ubuntu
        file: ~/.ssh/id_rsa.pub
      user-data:
        file: ../cloud-init/bingo-node.yaml
    node_count: 2
    allocation_policy: ["ru-central1-b"]
    deploy_policy:
      max_unavailable: 1
      max_expansion: 1

instances:
  prod-bastion:
    ansible_groups:
      - bastion
    family_id: ubuntu-2204-lts
    resources:
      cores: 2
      memory: 1 #Gb
      disk_size: 30 #Gb
    network:
      subnet: prod-bingo-subnet
      nat: true
    metadata: 
      ssh-keys: 
        username: ubuntu
        file: ~/.ssh/id_rsa.pub
  # prod-nginx:
  #   ansible_groups:
  #     - balancer
  #   family_id: ubuntu-2204-lts
  #   resources:
  #     cores: 2
  #     memory: 1 #Gb
  #     disk_size: 30 #Gb
  #   network:
  #     subnet: prod-bingo-subnet
  #     nat: true
  #   metadata: 
  #     ssh-keys: 
  #       username: ubuntu
  #       file: ~/.ssh/id_rsa.pub
  prod-postgresql:
    ansible_groups:
      - postgresql
    family_id: ubuntu-2204-lts
    hostname: postgres
    resources:
      cores: 2
      core_fraction: 50
      memory: 8 #Gb
      disk_size: 30 #Gb
      disk_type: "network-hdd"
    network:
      subnet: prod-bingo-subnet
      nat: false
    metadata: 
      ssh-keys: 
        username: ubuntu
        file: ~/.ssh/id_rsa.pub
      user-data:
        file: ../cloud-init/postgres.yaml  
  # monitoring:
  #   ansible_groups:
  #     - monitoring
  #   family_id: ubuntu-2204-lts
  #   resources:
  #     cores: 2
  #     memory: 4 #Gb
  #     disk_size: 100 #Gb
  #   network:
  #     subnet: prod-bingo-subnet
  #   metadata: 
  #     ssh-keys: 
  #       username: ubuntu
  #       file: ~/.ssh/id_rsa.pub