# - hosts: bingo,postgresql
#   tasks: 
#     - import_tasks: configs/playbook.yml
#   vars_files:
#     -  "{{ lookup('ansible.builtin.env', 'env_folder', default=Undefined) }}/envs/dev/ansible.vars.yml"

- name: configs upload
  import_playbook: configs/playbook.yml
  vars:
    pg_username: bingo
    pg_dbname: bingo
    pg_password: pass
    bingo_source: https://storage.yandexcloud.net/final-homework/bingo
- name: postgresql provisioning
  import_playbook: postgresql/playbook.yml
  vars:
    pg_username: bingo
    pg_dbname: bingo
    pg_password: pass
    bingo_source: https://storage.yandexcloud.net/final-homework/bingo