# - hosts: bingo,postgresql
#   tasks: 
#     - import_tasks: configs/playbook.yml
#   vars_files:
#     -  "{{ lookup('ansible.builtin.env', 'env_folder', default=Undefined) }}/envs/dev/ansible.vars.yml"
- name: Waiting Machines SSH
  hosts: all
  gather_facts: false
  tasks:
    - name: Waiting For SSH connection
      ansible.builtin.wait_for_connection:
        timeout: 300
- name: configs upload
  import_playbook: configs/playbook.yml

- name: balancer provisioning
  import_playbook: balancer/playbook.yml

- name: postgresql provisioning
  import_playbook: postgresql/playbook.yml

- name: monitoring provisioning
  import_playbook: monitoring/playbook.yml